#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""官方桌面链装配：web-apps deploy 产物 → rawfile/onlyoffice/webapps

替代 POC pack_web.py。流程：
  1. third_party/web-apps/deploy/web-apps/（官方 grunt 产物）
  2. 删除  ie/mobile/embed 子变体（官方 build_js.py:65-66 同）
  3. apps/api/documents/index.html.desktop → index.html（官方 build_js.py:68 同）
  4. 编辑器 main/index.html 注入 ascshim.js（<head> 前导；不改官方源）
  5. 复制到 rawfile/onlyoffice/webapps
  6. loginpage/deploy/index.html → rawfile/onlyoffice/index.html（欢迎页）
"""
import os
import shutil
import argparse

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SRC = os.path.join(ROOT, 'third_party', 'web-apps', 'deploy', 'web-apps')
SDK_SRC = os.path.join(ROOT, 'third_party', 'sdkjs', 'deploy', 'sdkjs')
DST = os.path.join(ROOT, 'entry', 'src', 'main', 'resources', 'rawfile', 'onlyoffice')
W3D = os.path.join(DST, 'webapps')
SDK_DST = os.path.join(DST, 'sdkjs')
LOGIN = os.path.join(ROOT, 'third_party', 'desktop-apps', 'common', 'loginpage', 'deploy', 'index.html')
FONT_DST = os.path.join(DST, 'fonts')          # GlobalLoaders.fontFilesPath - ../fonts/
SYSTEM_FONTS_DIR = '/usr/share/fonts/truetype/liberation'
# 顺序必须 R,I,B,BI（ascshim __fonts_files 注入数组与 FONT_INFOS 的 indexI/indexB 下标一致）
FONT_FILES = ['LiberationSans-Regular.ttf', 'LiberationSans-Italic.ttf',
              'LiberationSans-Bold.ttf', 'LiberationSans-BoldItalic.ttf',
              'LiberationSerif-Regular.ttf', 'LiberationSerif-Italic.ttf',
              'LiberationSerif-Bold.ttf', 'LiberationSerif-BoldItalic.ttf',
              'LiberationMono-Regular.ttf', 'LiberationMono-Italic.ttf',
              'LiberationMono-Bold.ttf', 'LiberationMono-BoldItalic.ttf']

# 字体注册表（引擎 Externals.js checkAllFonts 契约）
FONT_INFOS = [
    ["Arial", 0, 0, 1, 0, 2, 0, 3, 0],
    ["Liberation Sans", 0, 0, 1, 0, 2, 0, 3, 0],
    ["Times New Roman", 4, 0, 5, 0, 6, 0, 7, 0],
    ["Courier New", 8, 0, 9, 0, 10, 0, 11, 0],
    ["Symbol", 0, 0, 0, 0, 0, 0, 0, 0],
    ["Wingdings", 0, 0, 0, 0, 0, 0, 0, 0],
]
FONT_GUID_ODTTF = bytes([0xA0, 0x66, 0xD6, 0x20, 0x14, 0x96, 0x47, 0xFA, 0x95, 0x69, 0xB8, 0x50, 0xB0, 0x41, 0x49, 0x48])


def make_font_selection_bin(fonts):
    """最小 g_fonts_selection_bin（CFontSelect v0 序列化，little-endian）
    ——与 POC 同契约（引擎服务器字体索引，在 AllFonts.js 里注入）"""
    import struct
    buf = struct.pack('<I', len(fonts))
    for name in fonts:
        n = name.encode('utf-16-le')
        p = (name.lower().replace(' ', '') + '.ttf').encode('utf-16-le')
        buf += struct.pack('<I', len(n)) + n
        buf += struct.pack('<I', len(p)) + p
        buf += struct.pack('<I', 0)                # m_lIndex
        buf += struct.pack('<I', 0)                # italic
        buf += struct.pack('<I', 0)                # bold
        buf += struct.pack('<I', 0)                # fixed
        buf += struct.pack('<I', 10) + b'\x00' * 10  # panose
        buf += struct.pack('<IIII', 0, 0, 0, 0)    # unicode ranges
        buf += struct.pack('<II', 0, 0)            # codepage ranges
        buf += struct.pack('<HH', 400, 0)          # weight, width
        buf += struct.pack('<HHHHHHHH', 0, 1, 0, 0, 0, 0, 0, 0)  # family/format/avg/asc/desc/line/xh/cap
    import base64
    return base64.b64encode(buf).decode('ascii')


def pre_xor_font(path):
    """SDK 假设服务器字体已 guidOdttf 预加密（前 32B XOR）；明文会被 decode 破坏"""
    try:
        with open(path, 'rb') as f:
            data = bytearray(f.read())
    except OSError:
        return False
    n = min(32, len(data))
    for i in range(n):
        data[i] ^= FONT_GUID_ODTTF[i % 16]
    with open(path, 'wb') as f:
        f.write(data)
    return True


def gen_allfonts(fonts_infos):
    """生成 sdkjs/common/AllFonts.js —— 引擎 CheckAllFonts 契约（POC 同方案）。
    注意：字体名必须 JSON 引号（此前 str() 生成裸 [Liberation Sans,...] 实机 SyntaxError）"""
    import json
    sel_b64 = make_font_selection_bin([n[0] for n in fonts_infos])
    return ('// AllFonts.js (generated by build_editors_ohos.py)\n'
            'var g_font_files = [];\n'
            'var g_font_infos = [\n' +
            ',\n'.join(json.dumps(info) for info in fonts_infos) +
            '\n];\n'
            'window["g_fonts_selection_bin"] = "%s";\n' % sel_b64)

DELDIRS = ['ie', 'mobile', 'embed']
APP_MAIN = ['documenteditor', 'spreadsheeteditor', 'presentationeditor']


def copy_tree(src, dst):
    shutil.copytree(src, dst, dirs_exist_ok=True, symlinks=True)


def inject_ascshim(html_path):
    """在 <head> 注入 ascshim.js（相对路径：apps/<app>/main/ → ../../../../ascshim.js）"""
    return inject_script_src(html_path, '../../../../ascshim.js')


def inject_script_src(html_path, src_rel):
    """在 <head> 后注入 <script src=...>（幂等）"""
    with open(html_path, encoding='utf-8') as f:
        content = f.read()
    if 'ascshim.js' in content:
        return False
    marker = '<head>'
    inject = '<script src="%s"></script>\n' % src_rel
    content = content.replace(marker, marker + '\n' + inject, 1)
    with open(html_path, 'w', encoding='utf-8') as f:
        f.write(content)
    return True


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--no-copy-src', action='store_true', help='仅注入 ascshim（跳过重新复制）')
    args = ap.parse_args()

    if not os.path.isdir(SRC):
        raise SystemExit('web-apps deploy 不存在：先运行 grunt（scripts/onlyoffice/desktop/grunt-build.sh）')

    # 1. 先清理 rawfile 旧 webapps（POC 版）
    if os.path.isdir(W3D):
        shutil.rmtree(W3D)
    os.makedirs(W3D, exist_ok=True)

    print('复制 web-apps 官方产物 → %s ...' % W3D)
    copy_tree(SRC, W3D)

    # 1.5 sdkjs deploy（--desktop 构建，含 Local/*.js 保存链）→ rawfile/onlyoffice/sdkjs
    if os.path.isdir(SDK_DST):
        shutil.rmtree(SDK_DST)
    copy_tree(SDK_SRC, SDK_DST)
    print('复制 sdkjs deploy → %s' % SDK_DST)

    # 2. 删除非桌面子变体（官方同）
    for root, dirs, _ in os.walk(W3D):
        for d in dirs:
            if d in DELDIRS:
                p = os.path.join(root, d)
                shutil.rmtree(p, ignore_errors=True)
                print('  删除 ' + os.path.relpath(p, W3D))

    # 3. api/documents index.html.desktop → index.html（官方 build_js.py:68）
    #    grunt 构建产物不含 .desktop——从源码树取
    doct_orig_src = os.path.join(ROOT, 'third_party', 'web-apps', 'apps', 'api', 'documents', 'index.html.desktop')
    doct_orig = os.path.join(W3D, 'apps', 'api', 'documents', 'index.html.desktop')
    doct_dst = os.path.join(W3D, 'apps', 'api', 'documents', 'index.html')
    if not os.path.isfile(doct_orig) and os.path.isfile(doct_orig_src):
        shutil.copy2(doct_orig_src, doct_orig)
    if os.path.isfile(doct_orig) and not os.path.isfile(doct_dst):
        shutil.copy2(doct_orig, doct_dst)
        print('  api/documents/index.html.desktop → index.html')

    # 4. 各 app main/index.html 注入 ascshim（若还没注入）
    injected = 0
    for app in APP_MAIN:
        p = os.path.join(W3D, 'apps', app, 'main', 'index.html')
        if os.path.isfile(p) and inject_ascshim(p):
            injected += 1
            print('  注入 ascshim.js → apps/%s/main/index.html' % app)
    # api/documents 外壳页（编辑 iframe 宿主）
    p = os.path.join(W3D, 'apps', 'api', 'documents', 'index.html')
    if os.path.isfile(p) and inject_ascshim(p):
        injected += 1
        print('  注入 ascshim.js → apps/api/documents/index.html')
    print('  injected %d pages' % injected)

    # 5. 字体（AllFonts.js + fonts/ 预加密）→ rawfile/onlyoffice/
    allfonts_dst = os.path.join(SDK_DST, 'common', 'AllFonts.js')
    if not os.path.isfile(allfonts_dst):
        os.makedirs(os.path.dirname(allfonts_dst), exist_ok=True)
        with open(allfonts_dst, 'w', encoding='utf-8') as f:
            f.write(gen_allfonts(FONT_INFOS))
        print('  生成 sdkjs/common/AllFonts.js (%d bytes)' % os.path.getsize(allfonts_dst))
    else:
        print('  sdkjs/common/AllFonts.js 已存在')

    os.makedirs(FONT_DST, exist_ok=True)
    for fn in FONT_FILES:
        src_font = os.path.join(SYSTEM_FONTS_DIR, fn)
        dst_font = os.path.join(FONT_DST, fn)
        if os.path.isfile(src_font):
            shutil.copy2(src_font, dst_font)
            pre_xor_font(dst_font)
    print('  字体 → %s (%d files)' % (FONT_DST, len(FONT_FILES)))

    # 6. 欢迎页 loginpage → rawfile/onlyoffice/index.html
    if os.path.isfile(LOGIN):
        dst = os.path.join(DST, 'index.html')
        shutil.copy2(LOGIN, dst)
        inject_script_src(dst, 'ascshim.js')
        print('  loginpage → %s (%d bytes)' % (dst, os.path.getsize(dst)))
    else:
        print('  !! loginpage 不存在：先运行 desktop-apps 的 grunt build')
        raise SystemExit('loginpage 未构建')

    print('完成。')


if __name__ == '__main__':
    main()
