#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate entry/src/main/resources/rawfile/onlyoffice/ascshim.js

拼接 scripts/onlyoffice/desktop/src/*.js（页面适配 JS 源码，按主题分文件）：
  00_boot.js   IIFE 引导 + cell 打开剖面（诊断）
  10_engine.js Gateway 踢闸（serverId/images 引擎闸门适配）
  20_bridge.js AscDesktopEditor 装配（方法表/官方 shim/字体注册表/字节桥）
  30_open.js   DI 打开链（loadConfig 补发/CDocInfo/权限/踢闸/m7 工具）
  40_save.js   保存/关闭链适配（SaveDocument 落盘/requestClose/错误拦截）
  50_init.js   初始化尾（AscNative 等待循环）

src 内以占位符接入脚本动态内容（一一对应下面 .replace）：
  @@METHOD_JS@@       方法表装配（asc_methods.txt 转 JS 方法体）
  @@SHIM@@            官方 InitJSContext shim（ascdesktop_shim_raw.js）
  @@FONT_FILES_JSON@@ 字体文件表（build_editors_ohos.FONT_INFOS → JSON）
  @@FONT_INFOS_JSON@@ 字体元数据表

产物校验：node --check（JS 语法硬校验，失败即非零退出；宿主机无 node 时降级告警）。
修改页面适配请改 src/*.js 后重新生成本脚本；**ascshim.js 是生成产物，勿手改**。
"""
import os
import json
import shutil
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, '..'))
from build_editors_ohos import FONT_INFOS  # noqa: E402
# 字体数组顺序必须 R,I,B,BI（FONT_INFOS 的 indexI/indexB 引用下标）——POC 实证顺序
FONT_FILES = [
    'LiberationSans-Regular.ttf', 'LiberationSans-Italic.ttf',
    'LiberationSans-Bold.ttf', 'LiberationSans-BoldItalic.ttf',
    'LiberationSerif-Regular.ttf', 'LiberationSerif-Italic.ttf',
    'LiberationSerif-Bold.ttf', 'LiberationSerif-BoldItalic.ttf',
    'LiberationMono-Regular.ttf', 'LiberationMono-Italic.ttf',
    'LiberationMono-Bold.ttf', 'LiberationMono-BoldItalic.ttf',
]
METHODS = [l.strip() for l in open(os.path.join(HERE, 'asc_methods.txt')) if l.strip()]
SHIM = open(os.path.join(HERE, 'ascdesktop_shim_raw.js'), encoding='utf-8').read()

# 桥协议：AscNative._call 返回 JSON 编码字符串（对象/数组→JSON；纯字符串→带引号 JSON）。
# JS 侧统一 JSON.parse 解包——保证页面拿到真值（如 GetExternalClouds → [] 而不是 '[]'）。
method_lines = []
# 需回灌 loginpage 面板的方法（官方 CEF：Recents_Dump → ExecuteJavaScript
# window.onupdaterecents(json)；loginpage 面板订阅 sdk.on('onupdaterecents') → sdk.fire 桥接）
FIRE_MAP = {
    'LocalFileRecents': 'onupdaterecents',
    'LocalFileRecovers': 'onupdaterecovers',
}
# RAW 方法：官方 CEF 返回 **JSON 文本字符串**，消费端自己 JSON.parse()（sdkjs
# JSON.parse(AscDesktopEditor.GetInstallPlugins()) 等）—— 桥层不得解包。
#   桥返回形式同时保持 JSON 文本（ascBridge.ets 对应 case 已按官方空态结构返回）。
RAW_METHODS = {'GetInstallPlugins', 'GetBackupPlugins'}
for m in METHODS:
    if m in RAW_METHODS:
        body = (' var r = window.AscNative && window.AscNative._call(' +
                '"%s", Array.prototype.slice.call(arguments));' % m +
                ' return r; };')
        method_lines.append('  window.__ascDesktopEditorMethods["%s"] = function() {' % m + body)
        continue
    body = (' var r = window.AscNative && window.AscNative._call(' +
            '"%s", Array.prototype.slice.call(arguments));' % m +
            ' var v; try { v = r ? JSON.parse(r) : r; } catch(e) { v = r; }')
    if m in FIRE_MAP:
        body += (' try { window["%s"] && window["%s"](v); } catch(e) {}'
                 % (FIRE_MAP[m], FIRE_MAP[m]))
    body += ' return v; };'
    method_lines.append('  window.__ascDesktopEditorMethods["%s"] = function() {' % m + body)

METHOD_JS = '\n'.join(method_lines)
SHIM_INDENTED = '\n'.join('    ' + ln for ln in SHIM.split('\n'))

SRC_DIR = os.path.join(HERE, 'src')
PARTS = ['00_boot.js', '10_engine.js', '20_bridge.js', '30_open.js', '40_save.js', '50_init.js']
OUT = os.path.join(HERE, '..', '..', '..', 'entry', 'src', 'main', 'resources', 'rawfile', 'onlyoffice', 'ascshim.js')


def build() -> str:
    js = '/* auto-generated by make_ascshim.py — do not edit */\n'
    js += ''.join(open(os.path.join(SRC_DIR, p), encoding='utf-8').read() for p in PARTS)
    return (js.replace('@@METHOD_JS@@', METHOD_JS)
               .replace('@@SHIM@@', SHIM_INDENTED)
               .replace('@@FONT_FILES_JSON@@', json.dumps(FONT_FILES))
               .replace('@@FONT_INFOS_JSON@@', json.dumps(FONT_INFOS)))


JS = build()
out = os.path.join(os.path.dirname(__file__), '..', '..', '..', 'entry', 'src', 'main', 'resources', 'rawfile', 'onlyoffice', 'ascshim.js')
open(out, 'w').write(JS)

# 语法硬校验：node --check（宿主机 node 为 web-apps 构建链依赖，必然存在）
if shutil.which('node'):
    import tempfile
    with tempfile.NamedTemporaryFile('w', suffix='.js', delete=False) as tf:
        tf.write(JS)
        tmp = tf.name
    rc = subprocess.run(['node', '--check', tmp], capture_output=True, text=True)
    if rc.returncode != 0:
        print(rc.stderr, file=sys.stderr)
        sys.exit(f'node --check FAILED on generated ascshim.js: {out}')
    print('node --check: OK')

print(f'total methods: {len(METHODS)}')
print(f'shim bytes: {len(SHIM)}')
print(f'parts: {", ".join(PARTS)}')
print(f'out: {out}')
